### ISSUE TITLE
Additional Documentation

### ISSUE THREAD

**Issue by fedoranimus** [rlamasb/Firebase.Xamarin#13]
Is there any documentation on how to use the Offline Database with this library?

Also, the `.WithAuth(...)` documentation seems to be incorrect, as this method cannot be chained from `.Child('...')`.

Will updates to the documentation be made to clarify these issues?

Thanks!

**Comment by dthall43** [comment]
You are correct that his documentation is incorrect. However I wish to provide a way to use WithAuth so that future people can understand.

There is a class called QueryExtensions that provides the ability to do extended queries. It has a method WithAuth(string:token).

`var result = QueryExtensions.WithAuth(dinos, auth.FirebaseToken).OnceAsync<Object>().Result`

**Comment by fedoranimus** [comment]
Excellent, thank you.
